### ISSUE TITLE
Wrong header size for BitField compression

### ISSUE THREAD

**Issue by mayeut** [jsummers/bmpsuite#1]
Hi,

The header size used for the following images is 40 bytes. Shouldn't it be 52 bytes ?
- g/rgb16-565.bmp
- g/rgb16-565pal.bmp
- g/rgb32bf.bmp
- q/rgb16-231.bmp
- q/rgb32-111110.bmp

The [BMP_file_format](https://en.wikipedia.org/wiki/BMP_file_format#DIB_header_.28bitmap_information_header.29) wikipedia article suggests so.

**Comment by jsummers** [comment]
I think that either 40 or 52 would be valid, but 40 is better. Microsoft abandoned the 52-byte header format, and I don't have any documentation about it. The bmpsuite files use the "BITMAPINFOHEADER" header format, which is always 40 bytes. In that version of BMP, the 12-byte BITFIELDS segment is not considered to be part of that header.

**Comment by mayeut** [comment]
Thanks, I finally figured this out reading carefully the Microsoft documentation. IMHO, the wikipedia article was misleading.
