### ISSUE TITLE
Incorrect value in Intent field?

### ISSUE THREAD

**Issue by sebras** [jsummers/bmpsuite#11]
I'm confused by the value bmpsuite assigns to [the `Intent` field](https://github.com/jsummers/bmpsuite/blob/master/bmpsuite.c#L1046) in `BitmapV5GHeader`. It is set to `4` and the comment implies that this means `Perceptual`. Did you mixed up `Intent` with  `GamutMappingIntent` where `4` means `LCS_GM_IMAGES`?

As I read the [specification](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-WMF/%5bMS-WMF%5d.pdf) `Intent` must be set according to `LogicalColorSpace` for which the valid values are:

* `0x00000000` for `LCS_CALIBRATED_RGB`
* `0x73524742` for `LCS_sRGB`
* `0x57696E20` for `LCS_WINDOWS_COLOR_SPACE`

And since you are using sRGB Chromaticity values perhaps `Intent` is better set to `LCS_sRGB`?

**Comment by sebras** [comment]
[Image Magick](https://github.com/ImageMagick/ImageMagick/blob/master/coders/bmp.c) and [Graphics Magick](https://sourceforge.net/p/graphicsmagick/code/ci/default/tree/coders/bmp.c) also uses those bogus values (`LCS_GM_BUSINESS == 1`, `LCS_GM_GRAPHICS == 2`, `LCS_GM_IMAGES == 4` and `LCS_GM_ABS_COLORIMETRIC == 8` As does [GIMP](https://gitlab.gnome.org/GNOME/gimp/blob/master/plug-ins/file-bmp/bmp-save.c#L533)..! 

Does this mean that the bug is actually in the specification?

**Comment by jsummers** [comment]
I think it must be an error in the WMF spec. The documentation for [BITMAPV5HEADER](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapv5header) is what I'm using.

**Comment by sebras** [comment]
> I think it must be an error in the WMF spec.

Yes, the spec you pointed to as well as all these other pieces of software seems to indicate the same.
I have since found an [unofficial specifcation](http://zig.tgschultz.com/bmp_file_format.txt) that also matches the specification you mention. That unofficial spec does document the Huffman1D, RLE24 and Alphabitfields compression methods though. :)

> The documentation for BITMAPV5HEADER is what I'm using.

Thanks for pointing me to that specification. I had yet to find it.

I'll close this issue now, since it was apparently me that misunderstood things.
