### ISSUE TITLE
Offset to color profile incorrect?

### ISSUE THREAD

**Issue by sebras** [jsummers/bmpsuite#12]
I'm confused by bmpsuite [subtracting 14](https://github.com/jsummers/bmpsuite/blob/master/bmpsuite.c#L1048) from the offset to the profile data. Why is this done?

As far as I can understand the [specification](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-WMF/%5bMS-WMF%5d.pdf) `ProfileData` should simply be a plain offset, not modified.

**Comment by jsummers** [comment]
ProfileData offset is measured from the start of BitmapV5Header. In BMP file format, BitmapV5Header starts at offset 14, following BITMAPFILEHEADER.

**Comment by sebras** [comment]
> ProfileData offset is measured from the start of BitmapV5Header. In BMP file format,
> BitmapV5Header starts at offset 14, following BITMAPFILEHEADER.

Ah, that pesky BITMAPFILEHEADER! Yes, that makes sense. Thanks for explaining,
I'll close this issue now. :)
