### ISSUE TITLE
pal8.bmp and pal8.png differ when opened in MS Paint

### ISSUE THREAD

**Issue by szali** [jsummers/bmpsuite#14]
When opening the generated g/pal8.bmp and the reference html/pal8.png (both with MS Paint which is quite an authority in BMP), and taking a screenshot of the magnified files to compare pixel values in an editor, some pixels have different green levels (e.g. pixel (7, 63) has green=42 in the png and green=43 in the bmp).

**Comment by jsummers** [comment]
Acknowledged. It isn't necessarily supposed to be an exact match, but I don't think there's any reason for the numbers to be different in this case.

**Comment by jsummers** [comment]
The pal8*.png images should be fixed by commit 8e9503e6eea2.

There might still be a few other images with the same type of problem -- I haven't reviewed them all yet.

**Comment by johnstiles-google** [comment]
Are you still interested in fixing these?
`rgb16-3103.png` and `rgb32-7187.png` also have low-bit differences compared to my expected output.
I'm comparing against Chromium's output, and I will defer to MS Paint if it renders differently. I don't have a Windows machine handy to verify against. (But I suspect they probably agree.)

**Comment by jsummers** [comment]
I don't know. It'd be nice to review them to see if they're off by more than I'd want, but it's a lot of trouble for something so minor.

For channels that are not exactly 1, 2, 4, or 8 bits, some rounding or dithering is necessary when you convert them to 8 bits. Not everything is going to do that the same way.
