### ISSUE TITLE
Chrome Crash

### ISSUE THREAD

**Issue by richard-gravy** [jsummers/bmpsuite#18]
Hello,
Is it expected that when I try to view the "descriptions" page of the suite, the tab almost immediately crashes with SIGBUS?

Chrome 111.0.5563.71 (Official Build) (32-bit)

**Comment by jsummers** [comment]
If that happens, it's an issue with Chrome, not with BMP Suite.

**Comment by richard-gravy** [comment]
True, I will close this as an upstream issue.
Might try to get a goog to look at it.
