### ISSUE TITLE
Huffman 1D bit order

### ISSUE THREAD

**Issue by LewisMCYoutube** [jsummers/bmpsuite#19]
I was surprised this hadn't been tested yet, so I tried opening the two Huffman 1D-compressed BMP files from the suite with OS/2 programs, which, considering the nature of the format, I think is an authoritative source. There's surprisingly lacking support for Huffman-compressed files even among the tools of the era, but from every program I've found that does support them, including the built-in OS/2 image viewer, the correct bit order is msb-first.

Here is pal1huffmsb.bmp, converted to a .gif file with the OS/2 Warp 4.0 image viewer.
![pal1huffmsb](https://user-images.githubusercontent.com/12817318/235032330-a4583871-617a-4b79-ad7f-6f80ff77a1f9.gif)

And this is pal1hufflsb.bmp, converted the same way.
![pal1hufflsb](https://user-images.githubusercontent.com/12817318/235032342-8f51a2e0-6e28-4cf8-b34f-8c0038debe1d.gif)
(That might not load properly with all browsers, so here it is converted to a .tif file from OS/2, and then to a .png file with GIMP:)
![pal1hufflsb](https://user-images.githubusercontent.com/12817318/235032567-203d03dc-116e-463d-be0a-cdeacb571d62.png)

The shareware image viewer/converter [PMView](http://www.pmview.com/) can read them and gives the same output, and can also write them (it's easier to reference, since it has a Windows version). [Here's](https://files.catbox.moe/0l93cc.bmp) an example of a new 1 bpp Huffman 1D-compressed BMP file written with PMView based on pal8os2v2-16-comp.bmp.

**Comment by pkasting** [comment]
This is excellent research. Jason, want to update the .html accordingly?

**Comment by jsummers** [comment]
Resolved in v2.8.
