### ISSUE TITLE
rgb24prof2.bmp does not match rgb24.png in Chrome and Firefox

### ISSUE THREAD

**Issue by jwatt** [jsummers/bmpsuite#6]
As displayed by Chrome and Firefox, the top-left corner of rgb24.png is red whereas the top-left corner of bmpsuite.html is green. (Red and green are swapped.) It's not clear to me if this is a bug in bmpsuite, a bug in Chrome and Firefox, or if there are different valid renderings.

**Comment by jsummers** [comment]
I think the notes for this are fairly clear, though maybe not if you are not familiar with the concept of color profiles. The image is intended to test whether or not the viewer supports embedded color profiles in BMP files. No web browser that I know of does.

I suppose it would be best if there were another reference image to cover the (very normal) case where the viewer does not support color profiles.

**Comment by pkasting** [comment]
Chrome has supported this properly for a while; this can be closed.  (I don't know if Firefox supports it or not, but that would be a bug in Firefox if not.)
