### ISSUE TITLE
Firefox's rendering of pal4rlecut.bmp and pal8rlecut.bmp

### ISSUE THREAD

**Issue by jwatt** [jsummers/bmpsuite#7]
Firefox's rendering of pal4rlecut.bmp and pal8rlecut.bmp doesn't exactly match any of the three options. The seem to match the first of their options, but with the black band across the top that can be seen in the third of their options.

Should Firefox's rendering be added as a fourth option to bmpsuite for these two images?

**Comment by jsummers** [comment]
Firefox isn't wrong, but I think its behavior is a little too obtuse to bless it with a reference image. I'll probably add a note to the effect that any amalgam of the reference images is probably acceptable.

**Comment by pkasting** [comment]
Note added accordingly; this can be closed.
