### ISSUE TITLE
Sweet project

### ISSUE THREAD

**Issue by boxerab** [jsummers/bmpsuite#8]
Thanks for making this available as open source.
I am currently looking for a BMP with embedded ICC profile.
Can you tell me where I can find one? Also, do you happen to know
how common it is for users to embed ICC in BMP ?

Thanks!
Aaron

**Comment by jsummers** [comment]
I've never seen a BMP with an embedded profile in the wild. I think they are very rare. But I could be wrong. There could be some environments where they are common.

There are two in bmpsuite (q/rgb24prof.bmp, q/rgb24prof2.bmp), though I can't absolutely guarantee that they are correctly formed.

**Comment by boxerab** [comment]
Thanks. I got it working, I think, but if nobody uses this feature, then I won't worry about it.
I guess everyone uses TIFF for colour management.
